### ISSUE TITLE
Typo in Tutorial command

### ISSUE THREAD

**Issue by vgutierrez9** [Scifabric/docs.pybossa.com#19]
Hi, there is a typo in the tutorial https://docs.pybossa.com/build/tutorial/
in reference to the command:
"Now that we have the project.json file ready, we can create the project:
pbs --server server **--apikey** key create_project"

should in fact be 

"Now that we have the project.json file ready, we can create the project:
pbs --server server **--api-key** key create_project"

I just wanted to bring this issue to light and would appreciate the fix!

**Comment by therealmarv** [comment]
thx @vgutierrez9 I fixed it based on your report! :)

**Comment by vgutierrez9** [comment]
awesome, thank you!
