### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by yjftsjthsd-g** [Scifabric/docs.pybossa.com#42]
On this page:
https://docs.pybossa.com/installation/guide/#speeding-up-the-site
docs/installation/guide.md

Under section "Speeding up the site", the line "PYBOSSA comes with a cache system that **it is** disabled by default." should probably be "PYBOSSA comes with a cache system that **is** disabled by default." ("it" is probably not intended to be there).

**Comment by teleyinex** [comment]
Thanks a lot @yjftsjthsd-g! 

We've now a PR that will fix it ;-)
